## 파일 입출력

In [7]:
import os
os.getcwd()

'C:\\Users\\spa84\\multicampus28\\python\\ml'

In [8]:
import pandas as pd

sample_df = pd.DataFrame({"col1" : [1,2], 'col2' : [3,4]})
sample_df

sample_df.to_csv('output/test_csv', index=False)

## 파일 불러오기

In [9]:
df = pd.read_csv('output/test_csv')
df

col1  col2
0     1     3
1     2     4

In [10]:
df_boston = pd.read_csv('data/boston.csv')
df_boston

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  394.63   2.94    33.4  
4       18.7  396.90   5.33    36.2  
..       ...     ...    ...     ...  
501     21.0  391.99   9.67    22.4  
502     21.0  396.90   9.08    20.6  
503     21.0  396.90   5.64    23.9  
504     21.0  393.45   6.48    22.0  
505     21.0  396.90   7.88    11.9  

[506 rows x 14 columns]

## 열 및 행선택
- CRIM, ZN, INDUS 열을 선택함

In [11]:
cols = ['CRIM', 'ZN', 'INDUS']
result = df_boston[cols]
result

CRIM    ZN  INDUS
0    0.00632  18.0   2.31
1    0.02731   0.0   7.07
2    0.02729   0.0   7.07
3    0.03237   0.0   2.18
4    0.06905   0.0   2.18
..       ...   ...    ...
501  0.06263   0.0  11.93
502  0.04527   0.0  11.93
503  0.06076   0.0  11.93
504  0.10959   0.0  11.93
505  0.04741   0.0  11.93

[506 rows x 3 columns]

- ZN = 18인 데이터

In [12]:
result = df_boston.loc[df_boston['ZN']==18.0]
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE   DIS  RAD    TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.09  1.0  296.0     15.3   

       B  LSTAT  target  
0  396.9   4.98    24.0

- AGE가 50 이상인 데이터

In [13]:
result = df_boston.loc[df_boston['AGE'] >= 50].reset_index(drop=True)
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
4    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
354  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
355  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
356  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
357  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
358  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       15.3  396.90   4.98    24.0  
1       17.8  396.90   9.14    21.6  
2       17.8  392.83   4.03    34.7  
3       18.7  396.90   5.33    36.2  
4       18.7  394.12   5.21    28.7  
..       ...     ...    ...     ...  
354     21.0  391.99   9.67    22.4  
355     21.0  396.90   9.08    20.6  
356     21.0  396.90   5.64    23.9  
357     21.0  393.45   6.48    22.0  
358     21.0  396.90   7.88    11.9  

[359 rows x 14 columns]

- INDUS가 5.0 이상이면서 B가 394이상인 데이터

- 결과 = 데이터프레임[(조건식1) & (조건식2)]

In [14]:
result = df_boston[(df_boston['INDUS']>=5.0) & (df_boston['B']>=394)].reset_index(drop=True)
result

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
1    0.08829  12.5   7.87   0.0  0.524  6.012  66.6  5.5605  5.0  311.0   
2    0.14455  12.5   7.87   0.0  0.524  6.172  96.1  5.9505  5.0  311.0   
3    0.11747  12.5   7.87   0.0  0.524  6.009  82.9  6.2267  5.0  311.0   
4    0.62976   0.0   8.14   0.0  0.538  5.949  61.8  4.7075  4.0  307.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
138  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999  6.0  391.0   
139  0.22438   0.0   9.69   0.0  0.585  6.027  79.7  2.4982  6.0  391.0   
140  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
141  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
142  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  target  
0       17.8  396.90   9.14    21.6  
1       15.2  395.60  12.43    22.9  
2       15.2  396.90  19.15    27.1  
3       15.2  396.90  13.27    18.9  
4       21.0  396.90   8.26    20.4  
..       ...     ...    ...     ...  
138     19.2  395.77  15.10    17.5  
139     19.2  396.90  14.33    16.8  
140     21.0  396.90   9.08    20.6  
141     21.0  396.90   5.64    23.9  
142     21.0  396.90   7.88    11.9  

[143 rows x 14 columns]

## loc와 iloc 활용

In [15]:
df_boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [16]:
%%timeit

# iloc활용해서 추출
result = df_boston.iloc[:3, :3]
result

55 µs ± 2.24 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [17]:
%%timeit

# loc활용해서 추출
result = df_boston.loc[[0,1,2], ['CRIM', 'ZN', 'INDUS']]
result

732 µs ± 34.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [18]:
# loc가 조건문을 걸기 더 편함
result = df_boston.loc[(df_boston['INDUS']>=5.0) & (df_boston['B']>=394) # 행
                        , ['CRIM', 'ZN', 'INDUS']].reset_index(drop=True) # 열
result

CRIM    ZN  INDUS
0    0.02731   0.0   7.07
1    0.08829  12.5   7.87
2    0.14455  12.5   7.87
3    0.11747  12.5   7.87
4    0.62976   0.0   8.14
..       ...   ...    ...
138  0.17783   0.0   9.69
139  0.22438   0.0   9.69
140  0.04527   0.0  11.93
141  0.06076   0.0  11.93
142  0.04741   0.0  11.93

[143 rows x 3 columns]

## 결측치 다루기

In [19]:
import numpy as np

np.random.seed(0) # 랜덤함수 돌리는데 첫 결과를 고정, 실험조건 동일하게 맞추기 위해
data = np.random.randint(0, 10, size=(10, 3)).astype(float)
print(data)

[[5. 0. 3.]
 [3. 7. 9.]
 [3. 5. 2.]
 [4. 7. 6.]
 [8. 8. 1.]
 [6. 7. 7.]
 [8. 1. 5.]
 [9. 8. 9.]
 [4. 3. 0.]
 [3. 5. 0.]]


In [20]:
data[data <= 3] = np.nan
print(data)

[[ 5. nan nan]
 [nan  7.  9.]
 [nan  5. nan]
 [ 4.  7.  6.]
 [ 8.  8. nan]
 [ 6.  7.  7.]
 [ 8. nan  5.]
 [ 9.  8.  9.]
 [ 4. nan nan]
 [nan  5. nan]]


In [21]:
df = pd.DataFrame(data, columns=['col1', 'col2', 'col3']) # 외부에서 새로운 데이터 가져옴

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   col1    7 non-null      float64
 1   col2    7 non-null      float64
 2   col3    5 non-null      float64
dtypes: float64(3)
memory usage: 368.0 bytes


In [22]:
df.isna().sum()

col1    3
col2    3
col3    5
dtype: int64

In [23]:
# 평균으로 결측치 채우기
avg = df.mean()
df = df.fillna(avg)
df

col1      col2  col3
0  5.000000  6.714286   7.2
1  6.285714  7.000000   9.0
2  6.285714  5.000000   7.2
3  4.000000  7.000000   6.0
4  8.000000  8.000000   7.2
5  6.000000  7.000000   7.0
6  8.000000  6.714286   5.0
7  9.000000  8.000000   9.0
8  4.000000  6.714286   7.2
9  6.285714  5.000000   7.2

## 행추출

In [24]:
df = pd.DataFrame({
    "이름": ["Evan", "Sara", "Chris", "Messi", "Woods", "Jordan"], 
    "국어": [70, 90, None, None, 100, 85], 
    "영어": [65, 100, None, 90, 70, 80]
})

df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0

In [25]:
df.loc[6, "이름":"영어"] = ["Kim", 50, 60]
df

이름     국어     영어
0    Evan   70.0   65.0
1    Sara   90.0  100.0
2   Chris    NaN    NaN
3   Messi    NaN   90.0
4   Woods  100.0   70.0
5  Jordan   85.0   80.0
6     Kim   50.0   60.0

- 반복문으로 실행, 하지만 pandas에서는 굳이 그렇게 할 필요 없음

In [26]:
# 국어점수가 90점 이상이면 "A"
# 국어점수가 80점~89점 "B"
# 국어점수가 70점~79점 "C"
# 나머지는 F

for i in range(len(df.index)):
    if df.loc[i, "국어"] >= 90:
        df.loc[i, "점수"] = "A"
    elif 80 <= df.loc[i, "국어"] <= 89:
        df.loc[i, "점수"] = "B"
    elif 70 <= df.loc[i, "국어"] <= 79:
        df.loc[i, "점수"] = "C"
    else:
        df.loc[i, "점수"] = "F"

print(df)

       이름     국어     영어 점수
0    Evan   70.0   65.0  C
1    Sara   90.0  100.0  A
2   Chris    NaN    NaN  F
3   Messi    NaN   90.0  F
4   Woods  100.0   70.0  A
5  Jordan   85.0   80.0  B
6     Kim   50.0   60.0  F


- np.where(조건식,참, np.where(조건식,참, (np.where(조건식,참))))
- np.select(다중조건식, 다중결과값, default-->else조건)

In [27]:
condition_list = [(df["국어"] >= 90), (df['국어'] >= 80) & (df['국어'] < 90), (df['국어'] >= 70) & (df['국어'] < 80)]
choice_list = ["A", "B", "C"]
df['점수'] = np.select(condition_list, choice_list, default = "F")
df

이름     국어     영어 점수
0    Evan   70.0   65.0  C
1    Sara   90.0  100.0  A
2   Chris    NaN    NaN  F
3   Messi    NaN   90.0  F
4   Woods  100.0   70.0  A
5  Jordan   85.0   80.0  B
6     Kim   50.0   60.0  F

## 날짜 데이터 핸들링

In [28]:
# 문자열 변환
date_string = '2023-03-02'
print(type(date_string), end='\n\n')

datetime_obj = pd.to_datetime(date_string)
print(datetime_obj)
print(type(datetime_obj))

<class 'str'>

2023-03-02 00:00:00
<class 'pandas._libs.tslibs.timestamps.Timestamp'>


In [29]:
# 리스트 변환
date_string = ['2023-03-02']
print(type(date_string), end='\n\n')

datetime_obj = pd.to_datetime(date_string)
print(datetime_obj)
print(type(datetime_obj))

<class 'list'>

DatetimeIndex(['2023-03-02'], dtype='datetime64[ns]', freq=None)
<class 'pandas.core.indexes.datetimes.DatetimeIndex'>


## 데이터 가져오기
- raw_sales.csv

In [30]:
sales = pd.read_csv('./data/raw_sales.csv')
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   datesold      29580 non-null  object
 1   postcode      29580 non-null  int64 
 2   price         29580 non-null  int64 
 3   propertyType  29580 non-null  object
 4   bedrooms      29580 non-null  int64 
dtypes: int64(3), object(2)
memory usage: 1.1+ MB


In [31]:
# 날짜 데이터로 변환
sales['datesold'] = pd.to_datetime(sales['datesold'])
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
dtypes: datetime64[ns](1), int64(3), object(1)
memory usage: 1.1+ MB


In [32]:
# 연도, 월, 일
sales['year'] = sales['datesold'].dt.year
sales['month'] = sales['datesold'].dt.month
sales['day'] = sales['datesold'].dt.day
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


## shift 기능
- 정기적으로 들어오는 데이터와의 차이값 구하기 위해 활용

In [33]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df.head()

datesold   price
0 2007-02-07  525000
1 2007-02-27  290000
2 2007-03-07  328000
3 2007-03-09  380000
4 2007-03-21  310000

In [34]:
temp_df['shifted_v1'] = temp_df['price'].shift(1, fill_value=0).astype(int)
temp_df['diff'] = temp_df['price'] - temp_df['shifted_v1']
temp_df.head()

datesold   price  shifted_v1    diff
0 2007-02-07  525000           0  525000
1 2007-02-27  290000      525000 -235000
2 2007-03-07  328000      290000   38000
3 2007-03-09  380000      328000   52000
4 2007-03-21  310000      380000  -70000

In [35]:
temp_df['shifted_v2'] = temp_df['price'].shift(2, fill_value=0).astype(int)
temp_df['diff2'] = temp_df['price'] - temp_df['shifted_v2']
temp_df.head()

datesold   price  shifted_v1    diff  shifted_v2   diff2
0 2007-02-07  525000           0  525000           0  525000
1 2007-02-27  290000      525000 -235000           0  290000
2 2007-03-07  328000      290000   38000      525000 -197000
3 2007-03-09  380000      328000   52000      290000   90000
4 2007-03-21  310000      380000  -70000      328000  -18000

In [36]:
temp_df = sales.loc[:, ['datesold', 'price']].copy()
temp_df['shifted_v3'] = temp_df['price'].shift(-1, fill_value=0).astype(int)
temp_df['shifted_v4'] = temp_df['price'].shift(-2, fill_value=0).astype(int)
temp_df.tail()

datesold   price  shifted_v3  shifted_v4
29575 2019-07-25  500000      560000      464950
29576 2019-07-25  560000      464950      589000
29577 2019-07-26  464950      589000      775000
29578 2019-07-26  589000      775000           0
29579 2019-07-26  775000           0           0

In [37]:
sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29580 entries, 0 to 29579
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   datesold      29580 non-null  datetime64[ns]
 1   postcode      29580 non-null  int64         
 2   price         29580 non-null  int64         
 3   propertyType  29580 non-null  object        
 4   bedrooms      29580 non-null  int64         
 5   year          29580 non-null  int32         
 6   month         29580 non-null  int32         
 7   day           29580 non-null  int32         
dtypes: datetime64[ns](1), int32(3), int64(3), object(1)
memory usage: 1.5+ MB


In [38]:
sales['한글날짜'] = sales['datesold'].dt.strftime('%Y년 %m월 %d일')
sales.head()

datesold  postcode   price propertyType  bedrooms  year  month  day  \
0 2007-02-07      2607  525000        house         4  2007      2    7   
1 2007-02-27      2906  290000        house         3  2007      2   27   
2 2007-03-07      2905  328000        house         3  2007      3    7   
3 2007-03-09      2905  380000        house         4  2007      3    9   
4 2007-03-21      2906  310000        house         3  2007      3   21   

            한글날짜  
0  2007년 02월 07일  
1  2007년 02월 27일  
2  2007년 03월 07일  
3  2007년 03월 09일  
4  2007년 03월 21일

## Covid 데이터

In [126]:
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import statsmodels
import scipy
import seaborn as sns

print(pd.__version__)
print(np.__version__)
print(matplotlib.__version__)
print(statsmodels.__version__)
print(scipy.__version__)
print(sns.__version__)

2.0.3
1.25.2
3.7.2
0.14.0
1.11.1
0.12.2


In [153]:
DATA_PATH = './'
covidtotals = pd.read_csv(DATA_PATH + "data/covidtotalswithmissings.csv")
covidtotals.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 210 entries, 0 to 209
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   iso_code         210 non-null    object 
 1   lastdate         210 non-null    object 
 2   location         210 non-null    object 
 3   total_cases      210 non-null    int64  
 4   total_deaths     210 non-null    int64  
 5   total_cases_pm   209 non-null    float64
 6   total_deaths_pm  209 non-null    float64
 7   population       210 non-null    float64
 8   pop_density      198 non-null    float64
 9   median_age       186 non-null    float64
 10  gdp_per_capita   182 non-null    float64
 11  hosp_beds        164 non-null    float64
dtypes: float64(7), int64(2), object(3)
memory usage: 19.8+ KB


In [154]:
pd.set_option('display.width', 40)
pd.set_option('display.max_columns', 20)
pd.set_option('display.max_rows', 20)
pd.options.display.float_format = '{:,.2f}'.format

In [155]:
covidtotals = covidtotals.set_index('iso_code')
    # iso_code열을 인덱스로 설정

In [156]:
covidtotals.head()

lastdate     location  \
iso_code                            
AFG       2020-06-01  Afghanistan   
ALB       2020-06-01      Albania   
DZA       2020-06-01      Algeria   
AND       2020-06-01      Andorra   
AGO       2020-06-01       Angola   

          total_cases  total_deaths  \
iso_code                              
AFG             15205           257   
ALB              1137            33   
DZA              9394           653   
AND               764            51   
AGO                86             4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   
ALB                 11.47   
DZA                 14.89   
AND                660.07   
AGO                  0.12   

            population  pop_density  \
iso_code                              
AFG      38,928,341.00        54.42   
ALB       2,877,800.00       104.87   
DZA      43,851,043.00        17.35   
AND          77,265.00       163.75   
AGO      32,866,268.00        23.89   

          median_age  gdp_per_capita  \
iso_code                               
AFG            18.60        1,803.99   
ALB            38.00       11,803.43   
DZA            29.10       13,913.84   
AND              NaN             NaN   
AGO            16.80        5,819.49   

          hosp_beds  
iso_code             
AFG            0.50  
ALB            2.89  
DZA            1.90  
AND             NaN  
AGO             NaN

### 결측치 처리
- 인구통계 컬럼에서 결측치 데이터를 확인
- 컬럼뱡향으로 결측치의 갯수를 파악함
- 5가지 인구통계 변수 중 3개가 누락된 곳, 4개가 누락된 곳 확인

In [157]:
totvars = ['location','total_cases','total_deaths','total_cases_pm','total_deaths_pm']
    # 코로나 관련 컬럼
demovars = ['population','pop_density','median_age','gdp_per_capita', 'hosp_beds']
    # 인구 관련 컬럼

In [158]:
covidtotals[demovars].isnull().sum(axis=0)

population         0
pop_density       12
median_age        24
gdp_per_capita    28
hosp_beds         46
dtype: int64

In [159]:
covidtotals.iloc[2:4, :]

lastdate location  \
iso_code                        
DZA       2020-06-01  Algeria   
AND       2020-06-01  Andorra   

          total_cases  total_deaths  \
iso_code                              
DZA              9394           653   
AND               764            51   

          total_cases_pm  \
iso_code                   
DZA               214.22   
AND             9,888.05   

          total_deaths_pm  \
iso_code                    
DZA                 14.89   
AND                660.07   

            population  pop_density  \
iso_code                              
DZA      43,851,043.00        17.35   
AND          77,265.00       163.75   

          median_age  gdp_per_capita  \
iso_code                               
DZA            29.10       13,913.84   
AND              NaN             NaN   

          hosp_beds  
iso_code             
DZA            1.90  
AND             NaN

In [160]:
demovars_misscnt = covidtotals[demovars].isnull().sum(axis=1)
demovars_misscnt.value_counts()

0    156
1     24
2     12
3     10
4      8
Name: count, dtype: int64

### 미션 1.
- 결측치가 3개 이상인 데이터를 추출하세요!
- 추출할 컬럼은 ['location'] + demovars

In [161]:
type(demovars_misscnt)

pandas.core.series.Series

In [162]:
demovars_misscnt >= 3

iso_code
AFG    False
ALB    False
DZA    False
AND     True
AGO    False
       ...  
VNM    False
ESH     True
YEM    False
ZMB    False
ZWE    False
Length: 210, dtype: bool

In [163]:
covidtotals.loc[demovars_misscnt >= 3, ['location'] + demovars].T
    # demovars_misscnt의 index와 covidtotals의 index가 공통된 ISO코드로 되어있으므로 매칭

iso_code             AND       AIA  \
location         Andorra  Anguilla   
population     77,265.00 15,002.00   
pop_density       163.75       NaN   
median_age           NaN       NaN   
gdp_per_capita       NaN       NaN   
hosp_beds            NaN       NaN   

iso_code                                    BES  \
location        Bonaire Sint Eustatius and Saba   
population                            26,221.00   
pop_density                                 NaN   
median_age                                  NaN   
gdp_per_capita                              NaN   
hosp_beds                                   NaN   

iso_code                           VGB  \
location        British Virgin Islands   
population                   30,237.00   
pop_density                     207.97   
median_age                         NaN   
gdp_per_capita                     NaN   
hosp_beds                          NaN   

iso_code                   FRO  \
location        Faeroe Islands   
population           48,865.00   
pop_density              35.31   
median_age                 NaN   
gdp_per_capita             NaN   
hosp_beds                  NaN   

iso_code                     FLK  \
location        Falkland Islands   
population              3,483.00   
pop_density                  NaN   
median_age                   NaN   
gdp_per_capita               NaN   
hosp_beds                    NaN   

iso_code              GIB        GRL  \
location        Gibraltar  Greenland   
population      33,691.00  56,772.00   
pop_density      3,457.10       0.14   
median_age            NaN        NaN   
gdp_per_capita        NaN        NaN   
hosp_beds             NaN        NaN   

iso_code             GGY          IMN  \
location        Guernsey  Isle of Man   
population     67,052.00    85,032.00   
pop_density          NaN       147.87   
median_age           NaN          NaN   
gdp_per_capita       NaN          NaN   
hosp_beds            NaN          NaN   

iso_code              JEY  \
location           Jersey   
population     101,073.00   
pop_density           NaN   
median_age            NaN   
gdp_per_capita        NaN   
hosp_beds             NaN   

iso_code                XKX  \
location             Kosovo   
population     1,932,774.00   
pop_density             NaN   
median_age              NaN   
gdp_per_capita          NaN   
hosp_beds               NaN   

iso_code               MSR  \
location        Montserrat   
population        4,999.00   
pop_density            NaN   
median_age             NaN   
gdp_per_capita         NaN   
hosp_beds              NaN   

iso_code                             MNP  \
location        Northern Mariana Islands   
population                     57,557.00   
pop_density                       119.88   
median_age                           NaN   
gdp_per_capita                       NaN   
hosp_beds                            NaN   

iso_code                 TWN  \
location              Taiwan   
population     23,816,775.00   
pop_density              NaN   
median_age             42.20   
gdp_per_capita           NaN   
hosp_beds                NaN   

iso_code                             TCA  \
location        Turks and Caicos Islands   
population                     38,718.00   
pop_density                        37.31   
median_age                           NaN   
gdp_per_capita                       NaN   
hosp_beds                            NaN   

iso_code            VAT  \
location        Vatican   
population       809.00   
pop_density         NaN   
median_age          NaN   
gdp_per_capita      NaN   
hosp_beds           NaN   

iso_code                   ESH  
location        Western Sahara  
population          597,330.00  
pop_density                NaN  
median_age               28.40  
gdp_per_capita             NaN  
hosp_beds                  NaN

### 미션2.
- 코로나 관련 변수만 추출
- 결측값이 있는지 확인
- 결측값이 있는 국가가 하나 존재
- totvars 사용

In [164]:
covidtotals[totvars]

location  total_cases  \
iso_code                                
AFG          Afghanistan        15205   
ALB              Albania         1137   
DZA              Algeria         9394   
AND              Andorra          764   
AGO               Angola           86   
...                  ...          ...   
VNM              Vietnam          328   
ESH       Western Sahara           23   
YEM                Yemen          323   
ZMB               Zambia         1057   
ZWE             Zimbabwe          178   

          total_deaths  \
iso_code                 
AFG                257   
ALB                 33   
DZA                653   
AND                 51   
AGO                  4   
...                ...   
VNM                  0   
ESH                  1   
YEM                 80   
ZMB                  7   
ZWE                  4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   
...                  ...   
VNM                 3.37   
ESH                38.51   
YEM                10.83   
ZMB                57.50   
ZWE                11.98   

          total_deaths_pm  
iso_code                   
AFG                  6.60  
ALB                 11.47  
DZA                 14.89  
AND                660.07  
AGO                  0.12  
...                   ...  
VNM                  0.00  
ESH                  1.67  
YEM                  2.68  
ZMB                  0.38  
ZWE                  0.27  

[210 rows x 5 columns]

In [165]:
totvars_misscnt = covidtotals[totvars].isnull().sum(axis=1)
covidtotals.loc[totvars_misscnt > 0].T

iso_code                 HKG
lastdate          2020-05-26
location           Hong Kong
total_cases                0
total_deaths               0
total_cases_pm           NaN
total_deaths_pm          NaN
population      7,496,988.00
pop_density         7,039.71
median_age             44.80
gdp_per_capita     56,054.92
hosp_beds                NaN

### 코로나 발병률과 사망률

In [168]:
covidtotalsonly = covidtotals.loc[:, totvars]
covidtotalsonly['total_cases_q'] = pd.qcut(covidtotalsonly['total_cases'],
                                           labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                            q=5, precision=0)

covidtotalsonly['total_deaths_q'] = pd.qcut(covidtotalsonly['total_deaths'],
                                           labels = ['매우낮음', '낮음', '중간', '높음', '매우높음'],
                                            q=5, precision=0)
covidtotalsonly.head()

location  total_cases  \
iso_code                             
AFG       Afghanistan        15205   
ALB           Albania         1137   
DZA           Algeria         9394   
AND           Andorra          764   
AGO            Angola           86   

          total_deaths  \
iso_code                 
AFG                257   
ALB                 33   
DZA                653   
AND                 51   
AGO                  4   

          total_cases_pm  \
iso_code                   
AFG               390.59   
ALB               395.09   
DZA               214.22   
AND             9,888.05   
AGO                 2.62   

          total_deaths_pm  \
iso_code                    
AFG                  6.60   
ALB                 11.47   
DZA                 14.89   
AND                660.07   
AGO                  0.12   

         total_cases_q total_deaths_q  
iso_code                               
AFG                 높음             높음  
ALB                 중간             중간  
DZA                 높음           매우높음  
AND                 중간             중간  
AGO               매우낮음             낮음

In [171]:
cross = pd.crosstab(covidtotalsonly['total_cases_q'], covidtotalsonly['total_deaths_q'])
cross

total_deaths_q  매우낮음  낮음  중간  높음  매우높음
total_cases_q                         
매우낮음              34   7   1   0     0
낮음                12  19  10   1     0
중간                 1  13  15  13     0
높음                 0   0  12  24     6
매우높음               0   0   2   4    36

In [197]:
covidtotals.loc[(covidtotalsonly.total_deaths_q == '매우낮음') & (covidtotalsonly.total_cases_q == '중간')]

lastdate  \
iso_code               
CAF       2020-06-01   

                          location  \
iso_code                             
CAF       Central African Republic   

          total_cases  total_deaths  \
iso_code                              
CAF              1011             2   

          total_cases_pm  \
iso_code                   
CAF               209.33   

          total_deaths_pm  \
iso_code                    
CAF                  0.41   

           population  pop_density  \
iso_code                             
CAF      4,829,764.00         7.48   

          median_age  gdp_per_capita  \
iso_code                               
CAF            18.30          661.24   

          hosp_beds  
iso_code             
CAF            1.00

## Index Alignment
- 인덱스의 값끼리 연산이 이뤄지는 것을 말함. Pandas에서 제공

In [200]:
s1 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s2 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])

print(s1)
print(s2)

a    1
b    2
c    3
d    4
dtype: int64
d    4
c    3
b    2
a    1
dtype: int64


In [139]:
print (s1 + s2)
    # 일반적으로 생각하면 5555라는 결과가 나와야하지만 
    # 인덱스가 서로 같은 값끼리 연산이 이루어진다.

a    2
b    4
c    6
d    8
dtype: int64
